{
 "title": "Books API",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Rest API Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count[1m]))by (uri,method)"
    }
   ]
  },
  {
   "title": "HTTP All Books Latency (with alert)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{uri=\"/api/books\",method=\"GET\"}[1m]))"
    }
   ]
  },
  {
   "title": "HTTP Test Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{uri=\"/api/test\",method=\"GET\"}[1m]))"
    }
   ]
  },
  { "title": "Custom metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Search by title seconds sum (ns)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "books_service_books_search_by_title_seconds_sum"
    }
   ]
  },
  {
   "title": "Empty Search (with alert)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "books_service_api_books_get_count_total{matching_empty_books=\"1\"}"
    }
   ]
  },
  {
   "title": "Search by title in seconds (ns)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "books_service_books_search_by_title_seconds_count"
    }
   ]
  },
  {
   "title": "Search by title seconds max (ns)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "books_service_books_search_by_title_seconds_max"
    }
   ]
  },
  {
   "title": "Count total by \"title\" tag",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "books_service_api_books_get_count_total"
    }
   ]
  },
  {
   "title": "In store count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "books_service_books_in_store_count"
    }
   ]
  },
  {
   "title": "Test total",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "books_service_api_books_api_test_total",
     "legendFormat": "test method invocation count"
    }
   ]
  }
 ]
}